<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ChatGPT</name>
   <tag></tag>
   <elementGuidId>34710ddc-3949-4226-a4a2-25565df9c391</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rso']/div/div/div/div/table/tbody/tr[5]/td/div/h3/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ae68e908-9834-4f9d-b18e-aae88d091490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>l</value>
      <webElementGuid>b7c5bc4c-e069-44af-bde9-3e313db06b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://en.wikipedia.org/wiki/ChatGPT</value>
      <webElementGuid>c6b23777-824e-4639-9f48-9a48c16a302b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ved</name>
      <type>Main</type>
      <value>2ahUKEwi0qorQhP79AhX-7TgGHY13BsgQjBB6BAgTEAE</value>
      <webElementGuid>b64f7e40-6149-4f3e-9496-0450614cf877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ping</name>
      <type>Main</type>
      <value>/url?sa=t&amp;source=web&amp;rct=j&amp;url=https://en.wikipedia.org/wiki/ChatGPT&amp;ved=2ahUKEwi0qorQhP79AhX-7TgGHY13BsgQjBB6BAgTEAE</value>
      <webElementGuid>a7a3b7fc-993f-4895-8899-82a1d0362055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ChatGPT</value>
      <webElementGuid>52c40abb-e9b5-44d1-a74b-0b255188d2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rso&quot;)/div[@class=&quot;hlcw0c&quot;]/div[@class=&quot;MjjYud&quot;]/div[@class=&quot;g&quot;]/div[@class=&quot;BYM4Nd&quot;]/table[@class=&quot;jmjoTe&quot;]/tbody[1]/tr[@class=&quot;mslg&quot;]/td[@class=&quot;cIkxbf&quot;]/div[@class=&quot;usJj9c&quot;]/h3[1]/a[@class=&quot;l&quot;]</value>
      <webElementGuid>27c527d6-aa74-407c-a4a3-87cd82d049b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rso']/div/div/div/div/table/tbody/tr[5]/td/div/h3/a</value>
      <webElementGuid>ef81df0a-0570-4a33-b6bc-a92ce7980e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ChatGPT')]</value>
      <webElementGuid>90dc5bfe-f961-4ee0-b700-174afac8d9cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='India, officially the Republic of India (Hindi: Bhārat Gaṇarājya), ...'])[1]/following::a[1]</value>
      <webElementGuid>75d384b2-4579-447b-b712-de5248e4c33b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='India'])[1]/following::a[1]</value>
      <webElementGuid>df0771d4-0a75-415c-994b-c3d7005783cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='...'])[2]/preceding::a[1]</value>
      <webElementGuid>9ffb2b2e-1b6b-4126-9cda-586e5554aaeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ChatGPT']/parent::*</value>
      <webElementGuid>b194e7a1-97c8-41d3-9dc1-187a981b0965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://en.wikipedia.org/wiki/ChatGPT')]</value>
      <webElementGuid>45dec4cf-cf2b-4714-9180-bbf1ded195a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/div/h3/a</value>
      <webElementGuid>ad70d0b2-9f94-46df-8c4a-cd4529075173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://en.wikipedia.org/wiki/ChatGPT' and (text() = 'ChatGPT' or . = 'ChatGPT')]</value>
      <webElementGuid>4eae02e5-86a5-48bf-8ba9-79434d89cc77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
